name: Smash_by_Marvin2k0
author: Marvin2k0
version: 1.0
main: de.marvin2k0.smash.Smash
api-version: 1.15
commands:
  smash:
    permission: smash
  setlobby:
    permission: smash.setlobby
  setspawn:
    permission: smash.setspawn
  leave:
    permission: smash.leave
  setranked:
    permission: smash.setranked
  stats:
    permission: smash.stats
  setylevel:
    permission: smash.level
  setitemspawn:
    permission: smash.setitemspawn
  startgame:
    permission: smash.startgame
  endgame:
    permission: smash.endgame